nome = input('Digite algo: ')
print('O tipo primitivo dele é ', type(nome))
print('Só tem espaços? ', (nome.isspace()))
print('É um número? ' , (nome.isnumeric()))
print('É um alfabético? ',(nome.isalpha()))
print('É um alfanumérico? ', (nome.isalnum()))
print('Está em Capslock? ', (nome.isupper()))
print('Está em minúscula? ',(nome.islower()))
print('Está Capitalizada? ', (nome.istitle()))